blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import *
from . import views
app_name = "blog"


urlpatterns = [
    path('', home, name="home"),
    path('blogs/', blogs, name="blogs"),
    path('blogs/<str:slug>/', blog_details, name='blog_details'),
    path('category_blogs/<str:slug>/', category_blogs, name='category_blogs'),
    path('tag_blogs/<str:slug>/', tag_blogs, name='tag_blogs'),  
    path('tag/<slug:slug>/', tag_blogs, name='tag_blogs'),  
    path('add_reply/<int:blog_id>/<int:comment_id>/', add_reply, name='add_reply'),
    path('like_blog/<int:pk>/', like_blog, name='like_blog'),
    path('search/', search_blogs, name='search_blogs'),
    path('my_blogs/', my_blogs, name='my_blogs'),
    path('add_blog/', add_blog, name='add_blog'),
    path('update_blog/<str:slug>/', update_blog, name='update_blog'),
    path("blogcategories/", views.manage_categories, name="manage_categories"),
    path("blogcategories/delete/<int:category_id>/", views.delete_category, name="delete_category"),
    path("blogcategories/edit/<int:category_id>/", views.edit_category, name="edit_category"),  

]

blog_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('user_profile.urls')),
    path('', include("events.urls")),

    path('ckeditor/', include('ckeditor_uploader.urls')), 
]
# Esto sirve en produccion para que django sirva archivo estatáticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views
app_name = 'events'
urlpatterns = [
    path("add/", views.add_event, name="add_event"),
    path("", views.event_list, name="event_list"),
    path('my-events/', views.my_events, name='my_events'),
    path('update/<slug:slug>/', views.update_event, name='update_event'),
    path("categories/", views.manage_event_categories, name="manage_event_categories"),
    path("categories/delete/<int:category_id>/", views.delete_event_category, name="delete_event_category"),
    path("categories/edit/<int:category_id>/", views.edit_event_category, name="edit_event_category"),
]

user_profile/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views
from .views import *

app_name = 'user_profile'

urlpatterns= [
   path('user/<str:username>/', view_user_information, name='view_user_information'),
   path('login/', login_user, name='login'),
   path('logout/', logout_user, name='logout'),
   path('register_user/', register_user, name='register_user'),
   path('profile/  ', profile, name='profile'),
   path('change_profile_picture/', change_profile_picture, name='change_profile_picture'),
   path('view_user_information/<str:username>/', view_user_information, name="view_user_information"),
   path('follow_or_unfollow/<int:user_id>/', follow_or_unfollow_user, name='follow_or_unfollow_user'),
   path('user_notifications/', user_notifications, name='user_notifications'),
   path('mute_or_unmute_user/<int:user_id>/', mute_or_unmute_user, name='mute_or_unmute_user')
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from user_profile.models import User
from .slugs import generate_unique_slug

from ckeditor.fields import RichTextField 



class Category(models.Model): 
    title = models.CharField(max_length=150)
    slug = models.SlugField(null=True, blank=True)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    

class Tag(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(null=True, blank=True)
    created_date = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
    def save(self,*args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    

class Blog(models.Model):
    user = models.ForeignKey(
        User,
        related_name='user_blogs',
        on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        Category,
        related_name='category_blogs',
        on_delete=models.CASCADE
    )
    tags = models.ManyToManyField(
        Tag,
        related_name='tag_blogs',
        blank=True
    )
    likes = models.ManyToManyField(
        User,
        related_name='user_likes',
        blank=True
    )
    # pk_set = {1}
    title = models.CharField(
        max_length=250
    )
    slug = models.SlugField(null=True, blank=True)
    banner = models.ImageField(upload_to='blog_banners')
    description = RichTextField()
    created_date = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.title
    
    def save(self,*args, **kwargs):
        updating = self.pk is not None

        if updating:
            self.slug = generate_unique_slug(self, self.title, update=True)
            super().save(*args, **kwargs)
        else:
            self.slug = generate_unique_slug(self, self.title)
            super().save(*args, **kwargs)
    
class Comment(models.Model):
    user = models.ForeignKey(
        User,
        related_name='user_comments',
        on_delete=models.CASCADE,
    )
    blog = models.ForeignKey(
        Blog,
        related_name='blog_comments',
        on_delete=models.CASCADE
    )
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.text
    
    
class Reply(models.Model):
    user = models.ForeignKey(
        User,
        related_name='user_replies',
        on_delete=models.CASCADE
    )
    comment = models.ForeignKey(
        Comment,
        related_name='comment_replies',
        on_delete=models.CASCADE
    )
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.text
    


    

blog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Blog
from ckeditor.fields import RichTextField # type: ignore

class TextForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea, required=True)

class AddBlogForm(forms.ModelForm):
    description = RichTextField()
    class Meta:
        model = Blog
        fields = (
            "title",
            "category",
            "banner",
            "description"
        )
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            # para que tenga el mismo aspecto que todo el resto
        }

blog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.contrib import messages
from .models import Blog
from django.http import JsonResponse
from django.db.models import Q
from user_profile.models import User

from .models import (
    Blog,
    Category,
    Tag,
    Comment,
    Reply,
)
from .forms import TextForm, AddBlogForm

def home(request):
    blogs = Blog.objects.order_by('-created_date')[:3]
    tags = Tag.objects.order_by('-created_date')
    context = {
        "blogs" : blogs,
        "tags" : tags
    }
    return render(request, 'home.html', context)

def blogs(request):
    queryset = Blog.objects.order_by('-created_date')
    tags = Tag.objects.order_by('-created_date')
    page = request.GET.get('page', 1)
    paginator = Paginator(queryset, 4)
    
    try:
        blogs = paginator.page(page)
    except EmptyPage:
        blogs = paginator.page(1)
    except PageNotAnInteger:
        blogs = paginator.page(1)
        return redirect('blogs')

    context = {
        "blogs" : blogs,
        "tags" : tags,
        "paginator" : paginator
    }
    return render(request, 'blogs.html', context)

def category_blogs(request, slug):
    category = get_object_or_404(Category, slug=slug)
    queryset = category.category_blogs.all()
    tags = Tag.objects.order_by("-created_date")[:5]
    page = request.GET.get('page', 1)
    paginator = Paginator(queryset, 2)
    all_blogs = Blog.objects.order_by('-created_date')[:5]
    
    try:
        blogs = paginator.page(page)
    except EmptyPage:
        blogs = paginator.page(1)
    except PageNotAnInteger:
        blogs = paginator.page(1)
        return redirect('blogs')
    
    context = {
        "blogs": blogs,
        "tags": tags,
        "all_blogs": all_blogs,
        "category": category

    }
    return render(request, 'category_blogs.html', context)


def tag_blogs(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    queryset = tag.tag_blogs.all()
    tags = Tag.objects.order_by('-created_date')[:5]
    page = request.GET.get('page', 1)
    paginator = Paginator(queryset, 2)
    all_blogs = Blog.objects.order_by('-created_date')[:5]
    
    try:
        blogs = paginator.page(page)
    except EmptyPage:
        blogs = paginator.page(1)
    except PageNotAnInteger:
        blogs = paginator.page(1)
        return redirect('blogs')
      
    context = {
        "blogs": blogs,
        "tags": tags,
        "all_blogs": all_blogs

    }
    return render(request, 'category_blogs.html', context)


def blog_details(request, slug):
    form = TextForm()
    blog = get_object_or_404(Blog, slug=slug)
    category = Category.objects.get(id=blog.category.id )
    related_blogs = category.category_blogs.all()

    tags = Tag.objects.order_by('-created_date')[:5]
    recent_posts = Blog.objects.order_by('-created_date')[:5]  # Obteen los 5 posts mas recientes

    liked_by = request.user in blog.likes.all()

    if request.method == "POST" and request.user.is_authenticated:
        form = TextForm(request.POST)
        if form.is_valid():
            Comment.objects.create(
                user=request.user,
                blog=blog,
                text=form.cleaned_data.get('text')
            )
            return redirect('blog_details', slug=slug)
    context = {
        "blog": blog,
        "related_blogs": related_blogs,
        "tags": tags,
        "form": form,
        "liked_by": liked_by,
        "recent_posts": recent_posts  

    }
    return render(request, 'blog_details.html', context)


@login_required(login_url="login")
def add_reply(request, blog_id, comment_id):
    blog = get_object_or_404(Blog, id=blog_id)
    if request.method == "POST":
        form = TextForm(request.POST)
        if form.is_valid(): 

            comment = get_object_or_404(Comment, id=comment_id)
            Reply.objects.create(
                user=request.user,
                comment=comment,
                text=form.cleaned_data.get('text')
            )
    return redirect('blog_details', slug=blog.slug)

@login_required(login_url='login')
def like_blog(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    liked = False
    if request.user.is_authenticated:
        if request.user in blog.likes.all():
            blog.likes.remove(request.user)
        else:
            blog.likes.add(request.user)
            liked = True
    
    like_count = blog.likes.count()

    return JsonResponse({'liked': liked, 'like_count': like_count})

def search_blogs(request):
    search_key = request.GET.get('search', None)
    recent_blogs = Blog.objects.order_by('-created_date')
    tags = Tag.objects.order_by('-created_date')
    if search_key:
        blogs = Blog.objects.filter(
            Q(title__icontains=search_key) |
            Q(category__title__icontains=search_key) |
            Q(user__username__icontains=search_key) |
            Q(tags__title__icontains=search_key)
        ).distinct()

        context = {
            "blogs": blogs,
            "recent_blogs": recent_blogs,
            "tags": tags,
            "search_key": search_key

        }
        return render(request, 'search.html', context)
    else:
        return redirect('home')
    




@login_required(login_url="login")
def my_blogs(request):
    queryset = request.user.user_blogs.all()
    paginator = Paginator(queryset, 6)
    page = request.GET.get('page', 1)
    delete = request.GET.get('delete', None)

    if delete:
       
        blog = get_object_or_404(Blog, pk=delete)
        if request.user.pk != blog.user.pk:
            return redirect('home')
        
        blog.delete()
        messages.success(request, "your blog has been deleted!")
        return redirect('my_blogs')

    try:
        blogs = paginator.page(page)
    except EmptyPage:
        blogs = paginator.page(1)
    except PageNotAnInteger:
        blogs = paginator.page(1)
        return redirect('blogs')
    
    context = {
        "blogs": blogs,
        "paginator": paginator
    }

    return render(request, 'my_blogs.html', context)





@login_required(login_url='login')
def add_blog(request):
    form = AddBlogForm()

    if request.method == "POST":
        form = AddBlogForm(request.POST, request.FILES)
        if form.is_valid():
            tags = request.POST['tags'].split(',')
            user = get_object_or_404(User, pk=request.user.pk)
            category = get_object_or_404(Category, pk=request.POST['category'])
            blog = form.save(commit=False)
            blog.user = user
            blog.category = category
            blog.save()

            for tag in tags:
                tag_input = Tag.objects.filter(
                    title__iexact=tag.strip(),
                    slug=slugify(tag.strip())
                )
                if tag_input.exists():
                    t = tag_input.first()
                    blog.tags.add(t)

                else:
                    if tag != '':
                        new_tag = Tag.objects.create(
                            title = tag.strip(),
                            slug=slugify(tag.strip())
                        )
                        blog.tags.add(new_tag)


            messages.success(request, "blog addedd successfully")
            return redirect('blog_details', slug=blog.slug)
        else:
            print(form.errors)

    context = {
        "form": form

    }
    return render(request, 'add_blog.html', context)

@login_required(login_url='login')
def update_blog(request, slug):
    blog = get_object_or_404(Blog, slug=slug)
    form = AddBlogForm(instance=blog)

    if request.method == "POST":
        form = AddBlogForm(request.POST, request.FILES, instance=blog)
        
        if form.is_valid():
            
            if request.user.pk != blog.user.pk:
                return redirect('home')

            tags = request.POST['tags'].split(',')
            user = get_object_or_404(User, pk=request.user.pk)
            category = get_object_or_404(Category, pk=request.POST['category'])
            blog = form.save(commit=False)
            blog.user = user
            blog.category = category
            blog.save()

            for tag in tags:
                tag_input = Tag.objects.filter(
                    title__iexact=tag.strip(),
                    slug=slugify(tag.strip())
                )
                if tag_input.exists():
                    t = tag_input.first()
                    blog.tags.add(t)

                else:
                    if tag != '':
                        new_tag = Tag.objects.create(
                            title=tag.strip(),
                            slug=slugify(tag.strip())
                        )
                        blog.tags.add(new_tag)

            messages.success(request, "Blog updated successfully")
            return redirect('blog_details', slug=blog.slug)
        else:
            print(form.errors)


    context = {
        "form": form,
        "blog": blog
    }
    return render(request, 'update_blog.html', context)


def manage_categories(request):
    if request.method == "POST":
        title = request.POST.get("title")
        if title:
            Category.objects.get_or_create(title=title)  
        return redirect("manage_categories")

    categories = Category.objects.all().order_by("-created_date")
    return render(request, "manage_categories.html", {"categories": categories})


def edit_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    if request.method == "POST":
        new_title = request.POST.get("title")
        if new_title:
            category.title = new_title
            category.save()

notification/views.py
from django.shortcuts import render

# Create your views here.

templates/add_blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Añadir noticia {% endblock title %}

{% block content %}

<section class="add-blog">
    <div class="container">
        <div class="row py-5 justify-content-center">
            <div class="col-md-8">
                <form action="" method="POST" enctype="multipart/form-data"> 
                    {% comment %} sincronizado con form =AddblogForm.. request.FILES en views.py de blog {% endcomment %}
                    {{form.media}}
                    {% csrf_token %}
                    {% comment %} {% include 'messages.html'%} {% endcomment %}
                    <div class="form-group">
                        <label for="title">Título de la noticia</label>
                        <input class="form-control" type="text" name="title">
                        <p class="text-danger py-1">{{form.title.errors}}</p>
                    </div>
                    <div class="form-group">
                        <label for="title">Categoria</label>
                        <select class="form-control" name="category" id="category_id">
                        {% for category in categories %}
                            <option value="{{category.id}}">{{category.title}}</option>
                        {% endfor %}
                        <p class="text-danger py-1">{{form.category.errors}}</p>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="title">Contenido principal</label>
                        {{form.description|safe}}
                        <p class="text-danger py-1">{{form.description.errors}}</p>
                    </div>
                    <div class="form-group">
                        <label for="title">Banner</label>
                        <input class="form-control" class="form-control" type="file" name="banner">
                        <p class="text-danger py-1">{{form.banner.errors}}</p>
                    </div>
                    <div class="form-group">
                        <label for="title">Tags</label>
                        <textarea class="form-control" name="tags" id="" cols="30" rows="10" placeholder="Tags separados entre comas"></textarea>
                        <p class="text-danger py-1">{{form.tags.errors}}</p> 
                    </div>
                    <div class="form-group my-2">
                        <button type="submit" class="btn btn-primary btn-block">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/blogs.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Blogs {% endblock title %}

{% block content %}
    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                {% for blog in blogs %}
                {% include 'blog_card.html' %}
                {% endfor %}
                <div class="col-md-8 py-3 mb-2">
                  <h4 class="text-monospace">Total ({{paginator.object_list.count}})</h4>
                </div> 
                <div class="col-lg-12">
                  {% include 'pagination.html' %}
                </div>
              </div>
            </div>
 
          </div>
          {% include 'sidebar.html' %}
        </div>
      </div>
    </section>

{% endblock content %}

{% comment %} 
blog-Posts
grid-system
container
row
all-blog-posts






{% endcomment %}

templates/edit_event_category.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Editar Categoría{% endblock title %}

{% block content %}
<div class="container py-5">
    <h2>Editar Categoría</h2>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Nombre de la categoría</label>
            <input type="text" name="title" class="form-control" value="{{ category.title }}" required>
        </div>
        <button type="submit" class="btn btn-success mt-2">Guardar cambios</button>
        <a href="{% url 'events:manage_event_categories' %}" class="btn btn-secondary mt-2">Cancelar</a>
    </form>
</div>
{% endblock content %}

templates/footer.html
<!-- Footer -->
<footer class="hola">

<p class="footer-text">Copyright 2024 Sigfrid Art</p>

</footer>

templates/header.html
 <header class="">
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      
      <a class="navbar-brand" href="{% url 'blog:home' %}">
        <img src="https://i.ibb.co/XWXdqFc/LOGO.png" alt="LOGO" border="0" style="height: 70px; margin-right: 5px;" >
        <a class="navbar-brand" href="{% url 'blog:home' %}"><h2>Sigfrid Art<em></em></h2></a>
      </a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">

        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:home' %}">Home</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:blogs' %}">Noticias</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Categorias
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for category in categories %}
              <a class="dropdown-item" href="{% url 'blog:category_blogs' category.slug %}">{{category.title}}</a>
              {% endfor %}
            </div>
          </li>

          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{request.user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              
              <a class="dropdown-item" href="{% url 'user_profile:profile' %}">Perfil</a>
       
              <a class="dropdown-item" href="{% url 'user_profile:logout' %}">Cerrar sesión</a>
             
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'user_profile:login' %}">Iniciar sesión</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Logeate {% endblock title %}

{% block content %}

<section class="contact-us">
    <div class="container">
      <div class="row">
      
        <div class="col-lg-12">
          <div class="down-contact">
            <div class="row">
              <div class="col-lg-8">
                <div class="sidebar-item contact-form">
                  <div class="sidebar-heading">
                    <h2 class="login-text">Inicia sesión en tu cuenta</h2> 
                  </div>
                  <div class="content">
                    <form id="contact" action="" method="POST" novalidate>
                      {% csrf_token %}
                      <div class="row">
                        {% if messages %}
                        <div class="col-md-12 col-sm-12">
                          {% include 'message.html' %}
                        </div>
                        {% endif %}
                        <div class="col-md-12 col-sm-12">
                          <fieldset>
                            <input name="username" type="text" id="username_id" placeholder="Tu nombre o Email" >
                            <p class="error py-1 text-danger">{{form.username.errors}}</p>
                          </fieldset>
                        </div>
                        <div class="col-md-12 col-sm-12">
                          <fieldset>
                            <input name="password" type="password" id="password_id" placeholder="Tu contraseña" >
                            <p class="error py-1 text-danger">{{form.password.errors}}</p>
                          </fieldset>
                        </div>
                        <div class="col-lg-12">
                          <fieldset>
                            <button type="submit" id="form-submit" class="main-button btn-primary mr-3">Iniciar sesión</button>
                            <a href="{% url 'user_profile:register_user' %}" id="form-submit" class="main-button btn-primary">Registrarse</a>
                           <br></br><br></br><br></br><br></br>
                          </fieldset>
                        </div>
                    
                        
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


{% endblock content %}

templates/manage_categories.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Gestionar Categorias {% endblock title %}

{% block content %}
<section class="categories">
    <div class="container py-5">
        <h2 class="mb-4">Gestionar Categorias</h2>

        <!-- Formulario para anadir -->
        <form method="POST" class="mb-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Nueva categoria</label>
                <input type="text" name="title" class="form-control" placeholder="Nombre de la categoria" required>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Anadir</button>
        </form>

        <!-- Lista de categorias -->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Slug</th>
                    <th>Fecha creacion</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for category in categories %}
                <tr>
                    <td>{{ category.title }}</td>
                    <td>{{ category.slug }}</td>
                    <td>{{ category.created_date }}</td>
                    <td>
                        <a href="{% url 'blog:edit_category' category.id %}" class="btn btn-warning btn-sm">Editar</a>

                        <a href="{% url 'blog:delete_category' category.id %}"
                           class="btn btn-danger btn-sm"
                           onclick="return confirm('Seguro que quieres eliminar esta categoria?')">
                            Eliminar
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-center">No hay categorias todavia</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}

templates/manage_event_categories.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Gestionar Categorias de Eventos {% endblock title %}

{% block content %}
<section class="categories">
    <div class="container py-5">
        <h2 class="mb-4">Gestionar Categorias de Eventos</h2>

        <!-- Formulario para anadir -->
        <form method="POST" class="mb-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Nueva categoría</label>
                <input type="text" name="title" class="form-control" placeholder="Nombre de la categoria" required>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Anadir</button>
        </form>

        <!-- Lista de categorias -->
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Slug</th>
                    <th>Fecha creacion</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for category in event_categories %}
                <tr>
                    <td>{{ category.title }}</td>
                    <td>{{ category.slug }}</td>
                    <td>{{ category.created_date }}</td>
                    <td>
                        <a href="{% url 'events:edit_event_category' category.id %}" class="btn btn-warning btn-sm">Editar</a>
                        <a href="{% url 'events:delete_event_category' category.id %}"
                           class="btn btn-danger btn-sm"
                           onclick="return confirm('Seguro que quieres eliminar esta categoria?')">
                            Eliminar
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-center">No hay categorias todavia</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</section>
{% endblock content %}